openapi: 3.0.3
info:
  title: Budget API
  description: Budget API
  version: 0.0.1
  license:
    name: Unlicensed
    url: https://connorsmyth.com
servers:
  - url: 'https://budget.connorsmyth.com'
paths:

  /api/user/{id}:
    $ref: ./resources/user/user.yaml
