openapi: 3.0.3
info:
  title: Budget API
  description: Budget API
  version: 0.0.1
  license:
    name: Unlicensed
    url: https://connorsmyth.com
servers:
  - url: https://budget.connorsmyth.com
paths:
  /api/user:
    description: Create a user
    summary: Creates a single user
    post:
      operationId: postUser
      summary: Create a user
      description: Create single user
      tags:
        - user
      responses:
        '200':
          description: Returns the created user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    Uuid:
      type: string
      example: b9f89472-85bc-4b3b-826a-18d2dd73549f
      pattern: '[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}'
    User:
      type: object
      required:
        - uuid
      properties:
        uuid:
          $ref: '#/components/schemas/Uuid'
